import {  Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const roboto = Roboto(
  {
    weight: ['100', '200', '400', '600', '800']
  }
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}  antialiased`}
      >
        <header>
          <Navbar/>
        </header>
        <main className=" min-h-[calc(100vh-300px)] bg-base-200 pt-28">
                  {children}


        </main>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
